version: '3.8'

services:
  wallet-api:
    image: waltid/wallet-api:latest
    volumes:
      - ./wallet-api/config:/waltid-wallet-api/config
      - ./wallet-api/walt.yaml:/waltid-wallet-api/walt.yaml
      - ./wallet-api/data:/waltid-wallet-api/data
    networks:
      - epos_network   # Add this section to specify network

  issuer-api:
    platform: linux/x86_64
    image: waltid/issuer-api:latest
    volumes:
      - ./issuer-api/config:/waltid-issuer-api/config
    networks:
      - epos_network   # Add this section to specify network

  verifier-api:
    platform: linux/x86_64
    image: waltid/verifier-api:latest
    volumes:
      - ./verifier-api/config:/waltid-verifier-api/config
    networks:
      - epos_network   # Add this section to specify network

  waltid-web-wallet:
    image: waltid/waltid-web-wallet:latest
    environment:
      NUXT_PUBLIC_ISSUER_CALLBACK_URL: "http://wallet-api:$WALLET_FRONTEND_PORT"
      PORT: $WALLET_FRONTEND_PORT
    networks:
      - epos_network   # Add this section to specify network

  web-portal:
    platform: linux/x86_64
    image: waltid/portal:latest
    environment:
      NEXT_PUBLIC_VC_REPO: "http://vc-repo:$VC_REPO_PORT"
      NEXT_PUBLIC_ISSUER: "http://issuer-api:$ISSUER_API_PORT"
      NEXT_PUBLIC_VERIFIER: "http://verifier-api:$VERIFIER_API_PORT"
      NEXT_PUBLIC_WALLET: "http://waltid-web-wallet:$WALLET_FRONTEND_PORT"
      PORT: $WEB_PORTAL_PORT
    networks:
      - epos_network   # Add this section to specify network

  vc-repo:
    platform: linux/x86_64
    image: waltid/vc-repository:latest
    environment:
      PORT: $VC_REPO_PORT
    networks:
      - epos_network   # Add this section to specify network

  caddy:
    image: caddy:2
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - target: $WALLET_BACKEND_PORT
        published: $WALLET_BACKEND_PORT # wallet-api
        protocol: tcp
        mode: host

      - target: $ISSUER_API_PORT
        published: $ISSUER_API_PORT # issuer-api
        protocol: tcp
        mode: host

      - target: $VERIFIER_API_PORT
        published: $VERIFIER_API_PORT # verifier-api
        protocol: tcp
        mode: host

      - target: $WALLET_FRONTEND_PORT
        published: $WALLET_FRONTEND_PORT # waltid-web-wallet
        protocol: tcp
        mode: host

      - target: $WEB_PORTAL_PORT
        published: $WEB_PORTAL_PORT # web-portal
        protocol: tcp
        mode: host

      - target: $VC_REPO_PORT
        published: $VC_REPO_PORT # vc-repo
        protocol: tcp
        mode: host

    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - epos_network   # Add this section to specify network


networks:
  epos_network:
      name: epos_network
      external: true
